### ISSUE TITLE
mysterious error when using west

### ISSUE THREAD

**Issue by E3V3A** [sphinx-contrib/mscgen#6]
I have installed `sphinxcontrib-mscgen` using west, but when I run west, I keep getting the following error.

```bash
# west status

no changes added to commit (use "git add" and/or "git commit -a")
Error processing line 1 of
c:\python37\lib\site-packages\sphinxcontrib-mscgen-nspkg.pth:

  Traceback (most recent call last):
    File "c:\python37\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

Any ideas what is wrong?

It seem that you package is an important part of [west](https://github.com/zephyrproject-rtos/west), so a fix is quite urgent.

**Comment by carlescufi** [comment]
Sorry for the long delay @E3V3A. How exactly did you install this using west? west doesn't install any Python dependencies for you.
